name: CI/CD Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'         # <--- Sua pasta do front
      - 'k8s/frontend/**'
      - '.github/workflows/ci-frontend.yml'

jobs:
  build-push:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          # Nome da imagem:
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-frontend:latest

  deploy:
    name: Deploy Frontend to Azure
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_KEY }}
          script: |
            cd TRABALHO_DEVOPS
            git pull origin main
            
            # Aplica a pasta do front e o INGRESS GERAL
            kubectl apply -f k8s/frontend/
            kubectl apply -f k8s/ingress.yaml
            
            # Reinicia para pegar a imagem nova
            kubectl rollout restart deployment/frontend